name: Deploy MkDocs with uv

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true # Caches dependencies to speed up future builds

      - name: Install dependencies
        run: uv sync --frozen

      - name: Build and deploy MkDocs
        run: uv run mkdocs gh-deploy --force
